export const posts = [
  {
    slug: "why-african-businesses-need-social-media-automation",
    title: "Why African Businesses Need Social Media Automation in 2025",
    excerpt: "Most Nigerian SMEs post inconsistently or not at all. Here's why automation is the competitive edge you're missing.",
    category: "Strategy",
    date: "January 15, 2025",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80",
  },
  {
    slug: "how-to-grow-your-facebook-page-in-nigeria",
    title: "How to Grow Your Facebook Page in Nigeria: A Practical Guide",
    excerpt: "Facebook still dominates in Nigeria. Learn the exact posting frequency, content types, and boosting strategies that work.",
    category: "Facebook",
    date: "January 22, 2025",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80",
  },
  {
    slug: "ai-content-generation-for-small-businesses",
    title: "AI Content Generation: How Small Businesses Can Compete With Big Brands",
    excerpt: "You don't need a marketing team. AI tools like Groq Llama can generate weeks of content in minutes — here's how.",
    category: "AI & Content",
    date: "February 3, 2025",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
  },
  {
    slug: "tiktok-marketing-for-nigerian-brands",
    title: "TikTok Marketing for Nigerian Brands: What's Working Right Now",
    excerpt: "TikTok is exploding in Nigeria. Here's how to use short-form video to drive real business results without dancing.",
    category: "TikTok",
    date: "February 10, 2025",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1611605698335-8441fbfd049b?w=800&q=80",
  },
  {
    slug: "whatsapp-marketing-strategy-nigeria",
    title: "WhatsApp Marketing Strategy for Nigerian Businesses in 2025",
    excerpt: "WhatsApp has 90%+ penetration in Nigeria. Learn how to build a subscriber list and broadcast to thousands legally.",
    category: "WhatsApp",
    date: "February 18, 2025",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=800&q=80",
  },
  {
    slug: "social-media-posting-schedule-that-works",
    title: "The Social Media Posting Schedule That Actually Drives Engagement",
    excerpt: "Posting at the wrong time kills reach. Here's the optimal schedule for Facebook, Instagram, LinkedIn and TikTok in West Africa.",
    category: "Strategy",
    date: "March 1, 2025",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80",
  },
];
